require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.5
  Exclude:
    - "db/schema.rb"
    - "bin/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "tmp/**/*"

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
